spring:
  application:
    name: cg-ai-agent
  ai:
    dashscope:
      api-key:
      chat:
        options:
          model: qwen-plus

server:
  port: 8425
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cg.cgaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
